DROP TABLE IF EXISTS columns;
CREATE TABLE columns (
    id SERIAL PRIMARY KEY,
    key VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    mouseoverText TEXT,
    dataType VARCHAR(50) NOT NULL,
    isSort BOOLEAN DEFAULT FALSE,
    isFilter BOOLEAN DEFAULT FALSE,
    isVisible BOOLEAN DEFAULT TRUE,
    list jsonb,
    symbols jsonb,
    category VARCHAR(255),
    order_id integer,
    styleWidth integer,
    CONSTRAINT unique_key UNIQUE (key)
);
GRANT ALL PRIVILEGES ON columns TO web;

INSERT INTO columns (key, name, order_id, mouseoverText, dataType, isSort, isFilter, isVisible, list, symbols, category) VALUES
    ('name', 'Name', 0, null, 'string', true, false, true, '[]', '{}', null),
    ('aka', 'Name (AKA)', 1, null, 'string', false, false, true, '[]', '{}', null),
    ('imageUrl', 'Image', 2, null, 'image', false, false, true, '[]', '{}', null),
    ('experienceLevel', 'Experience Level', 3, null, 'string', false, false, true, '[]', '{}', null),
    ('purpose', 'Purpose', 9, null, 'string', false, true, true, '[]', '{}', null),
    ('purposeEggs', 'Purpose - Eggs', 10, null, 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', null),
    ('purposeMilk', 'Purpose - Milk', 10, null, 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', null),
    ('purposeWool', 'Purpose - Wool', 10, null, 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', null),
    ('purposeMeat', 'Purpose - Meat', 10, null, 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', null),
    ('sources', 'Sources', 99, null, 'string', false, false, false, '[]', '{}', null),
    ('physicalColor', 'Color', 0, null, 'string', false, false, false, '[]', '{}', 'Appearance'),
    ('physicalVarieties', 'Physical Varieties', 0, null, 'string', false, true, true, '[]', '{}', 'Appearance'),
    ('physicalComb', 'Comb', 1, null, 'string', false, true, true, '[]', '{}', 'Appearance'),
    ('physicalEars', 'Ears', 2, null, 'string', false, true, true, '[]', '{}', 'Appearance'),
    ('featherFeet', 'Feather Feet', 3, null, 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', 'Appearance'),
    ('PhysicalSkin', 'Skin', 4, null, 'string', false, true, false, '[]', '{}', 'Appearance'),
    ('physicalShanks', 'Shanks', 5, null, 'string', false, true, true, '[]', '{}', 'Appearance'),
    ('physicalMaturing', 'Maturing Rate', 6, null, 'string', false, true, true, '[]', '{}', 'Appearance'),
    ('sexlink', 'Sexlinked', 7, null, 'string', false, true, true, '[]', '{}', 'Appearance'),
    ('foragingAbility', 'Foraging Ability', 1, null, 'string', false, true, true, '["Fair", "Good", "Very Good", "Excellent"]', '{}', 'Behavior'),
    ('freeRange', 'Free Range', 2, null, 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', 'Behavior'),
    ('weeding', 'Weeding', 3, null, 'string', false, true, true, '[]', '{}', 'Behavior'),
    ('motheringAbility', 'Mothering Ability', 20, null, 'string', false, true, true, '["Poor", "Poor-Fair", "Fair", "Average", "Good", "Very Good", "Excellent"]', '{}', 'Behavior'),
    ('broody', 'Broodiness', 21, null, 'string', false, true, true, '[]', '{}', 'Behavior'),
    ('litterSize', 'Litter Size', 22, null, 'number', false, false, true, '[]', '{}', 'Behavior'),
    ('temperament', 'Temperament', 0, null, 'string', false, true, true, '[]', '{}', 'Behavior'),
    ('noise', 'Noise', 5, null, 'string', false, true, true, '[]', '{}', 'Behavior'),
    ('flyingAbility', 'Flying Ability', 4, null, 'string', false, true, true, '["None", "Maybe", "Very Good", "Excellent"]', '{}', 'Behavior'),
    ('eggColor', 'Egg Color', 0, null, 'string', true, true, true, '["White", "Brown", "Brown (Dark)", "Brown (Light)", "Cream", "Blue"]', '{}', 'Eggs'),
    ('eggSize', 'Egg Size', 1, null, 'string', true, true, true, '["Tiny", "Small", "Medium", "Large", "Extra Large"]', '{}', 'Eggs'),
    ('eggNumber', 'Egg Number', 2, null, 'number', true, true, true, '[]', '{}', 'Eggs'),
    ('fertilityRate', 'Fertility Rate', 4, null, 'string', false, false, true, '[]', '{}', 'Eggs'),
    ('bluishEggs', 'Bluish Eggs Rate', 10, null, 'string', false, false, true, '[]', '{}', 'Eggs'),
    ('tolerance', 'Tolerance', 0, null, 'string', false, true, true, '[]', '{}', 'Enviornment'),
    ('heatTolerance', 'Heat', 1, null, 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', 'Enviornment'),
    ('coldTolerance', 'Cold', 2, 'Cold Tolerance', 'boolean', false, true, true, '[]', '{"true": "✔️", "false": "❌"}', 'Enviornment'),
    ('BTU', 'B.T.U.', 10, 'Energy per Cord', 'number', true, true, true, '[]', '{}', 'Heat'),
    ('notes', 'Notes', 0, '', 'string', false, false, true, '[]', '{}', 'Notes'),
    ('breedClass', 'Breed Class', 50, '', 'string', false, true, true, '["Heritage", "Production"]', '{}', 'Purchasing'),
    ('rarity', 'Rarity', 50, null, 'string', false, true, true, '["Common", "Rare"]', '{}', 'Purchasing'),
    ('origin', 'Origin', 98, null, 'string', false, false, true, '[]', '{}', 'Purchasing'),
    ('conservationStatus', 'Conservation Status', 12, null, 'string', false, true, true, '["No Rank", "Abundant", "Plenty", "Recovering", "Watch", "Threatened", "Critical"]', '{}', 'Purchasing'),
    ('APAClass', 'APA Class', 11, null, 'string', false, true, true, '["Light", "Medium", "Heavy", "Bantam", "N/A"]', '{}', 'Purchasing'),
    ('showQuality', 'Show Quality', 10, null, 'string', false, false, true, '[]', '{}', 'Purchasing'),
    ('weightMale', 'Male (lb)', 1, null, 'number', false, true, true, '[]', '{}', 'Weight'),
    ('weightFemale', 'Female (lb)', 2, null, 'number', false, true, true, '[]', '{}', 'Weight'),
    ('weight', 'Weight (lbs)', 3, null, 'string', false, false, true, '[]', '{}', 'Weight'),
    ('weightHarvest', 'Harvest (lbs)', 4, null, 'string', false, false, true, '[]', '{}', 'Weight'),
    ('weightMature', 'Mature (lbs)', 5, null, 'string', false, false, true, '[]', '{}', 'Weight'),
    ('weightHarvest', 'Harvest (lbs)', 4, null, 'string', false, false, true, '[]', '{}', 'Weight'),
    ('heatQuality', 'Heat', 1, null, 'number', true, true, true, '[0, 1, 2, 3, 4, 5, 6]', '{"0":"-", "1":"★", "2":"★★", "3":"★★★", "4":"★★★★", "5":"★★★★★", "6":"★★★★★⭐"}', 'Wood'),
    ('starting', 'Starting', 2, null, 'number', true, true, true, '[]', '{"0":"-", "1":"★", "2":"★★", "3":"★★★", "4":"★★★★", "5":"★★★★★"}', 'Wood'),
    ('splitting', 'Splitting', 3, null, 'number', true, true, true, '[]', '{"0":"-", "1":"★", "2":"★★", "3":"★★★", "4":"★★★★", "5":"★★★★★", "6":"★★★★★⭐"}', 'Wood'),
    ('sparks', 'Sparks', 4, null, 'number', true, true, true, '[]', '{"0":"-", "1":"💥", "2":"💥💥", "3":"💥💥💥", "4":"💥💥💥💥", "5":"💥💥💥💥💥"}', 'Wood'),
    ('smoke', 'Smoke', 5, null, 'number', true, true, true, '[]', '{"0":"-", "1":"☁️", "2":"☁️☁️", "3":"☁️☁️☁️", "4":"☁️☁️☁️☁️", "5":"☁️☁️☁️☁️☁️"}', 'Wood'),
    ('woodRating', 'Overall Rating', 99, null, 'number', true, true, true, '[]', '{"0":"-", "1":"★", "2":"★★", "3":"★★★", "4":"★★★★", "5":"★★★★★"}', 'Wood'),

INSERT INTO columns (key, name, order_id, mouseoverText, dataType, isSort, isFilter, isVisible, list, symbols, category) VALUES
    ('colonyType', 'Colony Type', 6, null, 'string', true, true, true, '[]', '{}', Null),
    ('colonySize', 'Colony Size', 7, null, 'string', true, true, true, '[]', '{}', Null),
    ('colonyGrowthRate', 'Colony Growth Rate', 8, null, 'string', true, true, true, '[]', '{}', Null);